spring:
  application:
    name: JA_Product_Explorer_Backend
  datasource:
    url: ${DATABASE_URL:}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  servlet:
    context-path: /product-explorer

