spring:
  application:
    name: JA_Product_Explorer_Backend
    cosmos:
      url: ${COSMOSDB_URI:}
      key: ${COSMOSDB_KEY:}
  datasource:
    url: ${DATABASE_URL_H:}
    driver-class-name: ${DATABASE_DRIVER_CLASS_NAME:org.postgresql.Driver}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
    hikari:
      schema: ja_schema
      maximum-pool-size: 5
#  sql:
#    init:
#      platform: postgresql
#      schema-locations: classpath:/data.sql
#      mode: always
  viacep:
    url: https://viacep.com.br/ws/
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: ${DIALECT:org.hibernate.dialect.PostgreSQLDialect}
server:
  port: 8080
  servlet:
    context-path: /product-explorer

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

timezone: America/Sao_Paulo