name: Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - pom.xml
      - Dockerfile
      - .github/workflows/docker-publish.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract project name from pom.xml
        id: extract_project_name
        run: |
          PROJECT_NAME=$(grep -m1 -oP '(?<=<name>)[^<]+' pom.xml)
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner | toLower }}/"${{ env.PROJECT_NAME }}":${{ github.sha }} .

      - name: Push Docker image to GitHub Packages
        run: docker push ghcr.io/${{ github.repository_owner | toLower }}/"${{ env.PROJECT_NAME }}":${{ github.sha }}
