name: Publish Docker Image and Create Release

on:
  push:
    branches:
      - main

permissions:
  packages: write
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract project name from pom.xml
        id: extract_project_name
        run: |
          PROJECT_NAME=$(grep -m1 -oP '(?<=<artifactId>)[^<]+' pom.xml)
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV

      - name: Convert repository owner to lowercase
        id: convert_owner
        run: |
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "REPO_OWNER=$REPO
