name: Deploy Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and Push Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{HEROKU_APP_NAME}}
          email: ${{ vars.HEROKU_EMAIL }}
          dockerfile_directory: ./
          dockerfile_name: Dockerfile
          docker_options: "-e COSMOSDB_URI=${{vars.COSMOSDB_URI}} \
           -e COSMOSDB_KEY=${{secrets.COSMOSDB_KEY}} \
           -e DATABASE_URL=${{vars.DATABASE_URL}} \
           -e DATABASE_DRIVER_CLASS_NAME=${{vars.DATABASE_DRIVER_CLASS_NAME}} \
           -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} \
           -e DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}}"
          process_type: web

#      - uses: akhileshns/heroku-deploy@v3.13.15
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "ja-product-explorer-backend"
#          heroku_email: "aluis283@gmail.com"
#          branch: main
#          userdocker: true
#          docker_build_args: |
#            COSMOSDB_URI
#            COSMOSDB_KEY
#            DATABASE_URL
#            DATABASE_DRIVER_CLASS_NAME
#            DATABASE_USERNAME
#            DATABASE_PASSWORD
#        env:
#          COSMOSDB_URI: ${{vars.COSMOSDB_URI}}
#          COSMOSDB_KEY: ${{secrets.COSMOSDB_KEY}}
#          DATABASE_URL: ${{vars.DATABASE_URL}}
#          DATABASE_DRIVER_CLASS_NAME: ${{vars.DATABASE_DRIVER_CLASS_NAME}}
#          DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
#          DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
